auth/urls.py
from django.conf.urls import url, patterns
import views

urlpatterns = patterns("", )

collie/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', RedirectView.as_view(url='/project/index', permanent=False), name='index'),
                       url(r'^index/$', RedirectView.as_view(url='/project/index', permanent=False), name='index'),
                       # account login/logout
                       # url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html',
                       #                                                      'redirect_field_name': 'next'}),
                       # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/index/'}),
                       #et
                       url(r'^accounts/login/$', 'django_cas.views.login'),
                       url(r'^accounts/logout/$', 'django_cas.views.logout'),

                       url(r'^admin/', include(admin.site.urls)),


                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^module/', include('module.urls')),
                       url(r'^auth/', include('auth.urls')),
                       url(r'^profile/', include('profiles.urls')),
                       # url(r'^project/', include('project.urls', namespace='project')))
                       url(r'^project/', include('project.urls', namespace='project')),
                       url(r'^data/', include('data.urls', namespace='data')),
                       url(r'^table/', include('table.urls', namespace='table')))

project/urls.py
from django.conf.urls import url, patterns
from project import views
from project.views import HistoryDataTableView, HistoryView


urlpatterns = patterns('',
                       url(r'^index', views.index, name='index'),
                       url(r'^manage', views.manage_page, name='manage'),
                       url(r'^delete', views.delete, name='delete'),
                       url(r'^rename', views.rename, name='rename'),
                       url(r'^new', views.new_project, name='edit_page'),
                       url(r'^edit', views.edit_project, name='edit_page'),
                       url(r'^save', views.save_project, name='save'),
                       url(r'^detail', views.detail, name='get detail'),
                       url(r'^download', views.download, name='download'),
                       url(r'^permission/index', views.page_edit_permission, name='edit permission'),
                       url(r'^permission/grant', views.grant_project_permission, name='grant project permission'),
                       url(r'^permission/revoke', views.revoke_project_permission, name='revoke project permission'),
                       url(r'^execution/index', views.execution_index, name='flow_execution'),
                       url(r'^execution/pause', views.execution_pause, name='pause'),
                       url(r'^execution/cancel', views.execution_cancel, name='cancel'),
                       url(r'^execution/resume', views.execution_resume, name='resume'),
                       url(r'^execution/job/index', views.execution_job_index, name='job index'),
                       url(r'^execution/job/log', views.execution_job_log, name='job log'),
                       url(r'^execution/diagram', views.flow_execution_diagram, name='execution diagram'),
                       url(r'^execution/log', views.flow_execution_log, name='execution log'),
                       url(r'^flow/index', views.flow_index, name='flow'),
                       url(r'^flow/tree', views.flow_tree, name='get flow tree'),
                       url(r'^flow/diagram', views.flow_diagram, name='get flow diagram'),
                       url(r'^flow/options_execute', views.flow_execute_options, name='get flow execute options'),
                       url(r'^flow/colliexe_nodes', views.flow_colliexe_nodes, name='get flow colliexe nodes'),
                       url(r'^flow/execute', views.flow_execute, name='execute flow'),
                       url(r'^flow/schedule', views.flow_schedule, name='schedule flow'),
                       url(r'^executing/index', views.executing_page, name='executing'),
                       url(r'^scheduled/index', views.scheduled_page, name='scheduled'),
                       url(r'^scheduled/delete', views.scheduled_delete, name='remove scheduled'),
                       url(r'^history/index$', HistoryView.as_view(), name='index_history'),
                       url(r'^history/data$', HistoryDataTableView.as_view(), name="history_table"))

project/views.py
import Queue
import base64
import copy
from email.mime.text import MIMEText
import smtplib
import dateutil
import json
import logging
from django.core.mail import EmailMessage
import os
import shutil
import re
import traceback
import urllib
import urllib2
import zipfile
import datetime
# from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render_to_response
import time
from dateutil import tz, relativedelta
from django.views.defaults import permission_denied
from django.views.generic import TemplateView
from django_datatables_view.base_datatable_view import BaseDatatableView
from object_permissions import get_groups_any
from core.file_handler import checksum_file
from core.utils import get_file_content
from core.webhdfs import WebHdfs
from module.models import Module, ModuleVersions, ModuleHdfsFiles
from profiles.models import KerberosKeys, CollieGroup
from project.flows import ExecutionOptions, Job, Flow
from project.models import Project, ProjectVersions, ProjectFiles, ExecutionFlows, FlowLogs, ExecutionJobs, JobLogs, \
    Schedule, PROJECT_PERM_OWNER, PROJECT_PERM_USER
from settings import settings
from core.urllibr import encode

logger = logging.getLogger("collie")
COLLIEXE_EXECUTOR_URL = "http://" + settings.COLLIEXE_HOST + ":" + settings.COLLIEXE_PORT + "/executor"
COLLIEXE_SCHEDULE_URL = "http://" + settings.COLLIEXE_HOST + ":" + settings.COLLIEXE_PORT + "/schedule"
COLLIEXE_BROKERS_URL = "http://" + settings.COLLIEXE_HOST + ":" + settings.COLLIEXE_PORT + "/system"


@login_required()
def index(request):
    try:
        user = request.user
        username = user.username
        logger.info('project index page, user %s', username)

        if user.is_superuser:
            projects_valid = Project.objects.all()
        else:
            projects_valid = user.get_objects_any_perms(Project, perms=[PROJECT_PERM_OWNER, PROJECT_PERM_USER])

        projects = []
        for project in projects_valid:
            if project.status < 0:
                continue

            project_versions = ProjectVersions.objects.filter(project_id=project.id).order_by('-project_version')[:1]
            if len(project_versions) <= 0:
                continue
            project_version = project_versions[0]
            project_content = dict()
            project_content['project_name'] = project.name
            project_content['project_id'] = project_version.project_id
            project_content['project_version'] = project_version.project_version
            project_content['upload_user'] = project_version.upload_user
            project_content['upload_time'] = project_version.upload_time

            # found how many valid scheduled items
            project_id = project_version.project_id
            scheduled = Schedule.objects.filter(~Q(status='EXPIRED'), project_id=project_id)
            project_content['scheduled'] = len(scheduled)
            projects.append(project_content)

        context = {'project_list': projects}
        return render_to_response('project/project_index.html', context, context_instance=RequestContext(request))
    except Exception as e:
        logger.error("hit exception %s when get project index", e)
        raise


@login_required()
def manage_page(request):
    username = request.user.username
    logger.info("user %s visit project manage page", username)

    project_id = request.GET.get("project_id")
    version_id = request.GET.get("version_id")
    logger.info('get manage page, user %s, project %s, id %s', username, project_id, version_id)

    user = request.user
    project = Project.objects.get(id=project_id)
    if user.is_superuser:
        perms = [PROJECT_PERM_OWNER]
    else:
        perms = user.get_perms(project)

    if len(perms) <= 0:
        logger.error('no permission to enter')
        return permission_denied(request)

    if PROJECT_PERM_OWNER in perms:
        role = PROJECT_PERM_OWNER
    else:
        role = PROJECT_PERM_USER

    project_versions = ProjectVersions.objects.all().filter(project_id=project_id, project_version=version_id)
    project_version = project_versions.latest('project_version')
    diagram = project_version.diagram

    diagram_json = json.loads(diagram)
    jobs = diagram_json['jobs']
    connections = diagram_json['connections']

    # construct job info map
    job_info_map = {}
    for job in jobs:
        job_id = job['job_id']
        job_info_map[job_id] = job

    # found all job who has no followers
    job_has_follower_map = {}
    job_has_no_follower_map = {}
    for connection in connections:
        source_id = connection['source_id']
        job_has_follower_map[source_id] = True
    for job in jobs:
        job_id = job['job_id']
        if job_id in job_has_follower_map:
            continue
        job_has_no_follower_map[job_id] = job

    flows_root = []
    for job_id in job_has_no_follower_map.keys():
        job = job_info_map[job_id]

        # check there is schedule item of this flow
        schedule = Schedule.objects.filter(~Q(status='EXPIRED'), project_id=project_id, flow_id=job_id)
        has_scheduled = len(schedule) > 0
        flows_root.append({
            'job_id': job_id,
            'has_scheduled': has_scheduled,
            'name': job['name']
        })

    # get latest successful run date
    succeed_executions = ExecutionFlows.objects.filter(project_id=project.id, project_version=version_id,
                                                       status='SUCCEEDED').order_by('-end_time')
    latest_success_date = 'NA'
    if len(succeed_executions) > 0:
        latest_success_date = succeed_executions[0].end_time.replace(tzinfo=tz.gettz('Asia/Shanghai'))

    context = {
        'project': {
            'id': project.id,
            'version_id': version_id,
            'name': project.name,
            'permissions': 'ADMIN',
            'create_date': project.created_time,
            ### 'description': 'TODO',
            'modify_date': project_version.upload_time,
            # 'admins': '1.0',
            'latest_success_date': latest_success_date,
            'modify_by': project_version.upload_user,
            'role': role
        },
        'flows_root': flows_root
    }

    return render_to_response('project/project_manage.html', context, context_instance=RequestContext(request))


@login_required()
def page_edit_permission(request):
    project_id = request.GET.get('project_id')
    project = Project.objects.get(id=project_id)
    groups_owner = get_groups_any(project, perms=[PROJECT_PERM_OWNER])
    groups = []
    for group in groups_owner:
        groups.append({
            'name': group.name,
            'role': 'owner'
        })
    groups_user = get_groups_any(project, perms=[PROJECT_PERM_USER])
    for group in groups_user:
        groups.append({
            'name': group.name,
            'role': 'user'
        })
    context = {
        'groups': groups
    }
    return render_to_response('project/project_permission.html', context, context_instance=RequestContext(request))


@login_required()
@csrf_exempt
def grant_project_permission(request):
    username = request.user.username
    group_name = request.POST.get('group_name')
    project_id = request.POST.get('project_id')
    role = request.POST.get('role')
    logger.info('user %s grant group %s onto project id %s, role %s', username, group_name, project_id, role)

    if role != 'owner' and role != 'user':
        context = {
            'status': -1,
            'error': 'no such role found'
        }
        logger.error('failed to grant permission, coz no such role %s', role)
        return HttpResponse(json.dumps(context), mimetype='application/json')

    if role == 'owner':
        permission = PROJECT_PERM_OWNER
    else:
        permission = PROJECT_PERM_USER

    try:
        group = CollieGroup.objects.get(name=group_name)
    except ObjectDoesNotExist:
        context = {
            'status': -1,
            'error': 'no such group found'
        }
        logger.error('failed to grant permission, coz no such group %s', group_name)
        return HttpResponse(json.dumps(context), mimetype='application/json')

    project = Project.objects.get(id=project_id)
    group.revoke_all(project)
    group.grant(permission, project)
    context = {
        'status': 1
    }
    logger.info('successfully to grant permission')
    return HttpResponse(json.dumps(context), mimetype='application/json')


@login_required()
@csrf_exempt
def revoke_project_permission(request):
    user = request.user
    username = user.username
    project_id = request.POST.get('project_id')
    group_name = request.POST.get('group_name')
    logger.info('user %s revoke perm of group %s', username, group_name)

    try:
        group = CollieGroup.objects.get(name=group_name)
    except ObjectDoesNotExist:
        context = {
            'status': -1,
            'error': 'no such group found'
        }
        logger.error('failed to revoke permission, coz no such group %s', group_name)
        return HttpResponse(json.dumps(context), mimetype='application/json')

    project = Project.objects.get(id=project_id)
    group.revoke_all(project)
    context = {
        'status': 1
    }
    logger.info('successfully revoke permission')
    return HttpResponse(json.dumps(context), mimetype='application/json')


def get_proceedings(proceeding_map, current_id, job_info_map):
    if current_id not in proceeding_map:
        return []
    proceedings = proceeding_map[current_id]
    proceeding_infos = []
    for proceeding_job_id in proceedings['proceedings']:

project/templates/project/project_edit.html
{% extends "base.html" %}

{% block script %}
    <script src="{{ STATIC_URL }}js/project/project_edit.js?r=20151023"></script>
    <script src="{{ STATIC_URL }}js/project/project_execute.js"></script>
    <script src="{{ STATIC_URL }}js/project/diagram.js"></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/project_edit.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/project_execute.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/diagram.css" />
{% endblock %}

{% block header %}
    <a href="/project/index" title="Go to Projects" class="tip-bottom"><i class="icon-home"></i> Projects</a>
    <a href="#" title="Create Project" class="tip-bottom">Create Project</a>
{% endblock %}

{% block main_panel %}
    <div class="container-fluid">
    <div class="row-fluid">
        <div class="span8">
            <span class="badge badge-info" id="project_id">{{ project_id }}</span>
            <strong style="margin-left: 10px">{{ project_name }}</strong>
        </div>
        <div class="span4" style="text-align: right">
            <div id="execute_project" style="display: none;">
                <!-- a class="btn btn-group" style="margin-bottom: 10px; width: 80px; ">Execute</a -->
                <div class="btn-group" style="margin-bottom: 10px">
                    <button data-toggle="dropdown" class="btn btn-info dropdown-toggle">Execute <span class="caret"></span></button>
                    <ul class="dropdown-menu" style="text-align: left" id="flows">
                        <li class="flow" id="flow_temp" flow_name="" style="display: none"><a href="#">Action</a></li>
                    </ul>
                </div>
                <a id="edit_project" class="btn btn-primary" style="margin-bottom: 10px; width: 80px; display: none; ">Edit</a>
            </div>
            <a id="save_project" class="btn btn-success" style="margin-bottom: 10px; width: 80px; display: none; ">Save</a>
        </div>
    </div>
    <hr style="margin: 2px"/>
    <div class="row-fluid">
        <div class="span9">
            <div class="project-panel" id="project-panel">
                <div class="job" id="job_temp" style="display: none"><div class="dependency"></div></div>
            </div>
        </div>
        <div class="span3">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-th"></i></span>
                    <h5>Modules</h5>
                </div>
                <div class="widget-content">
                    <!-- TODO
                    <div class="row-fluid clearfix" style="margin: 2px">
                        <input class="span8" type="text"/>
                        <button class="btn btn-default btn-lg span3 pull-right" style="width: 80px">Search</button>
                    </div>
                    <hr style="margin: 5px"/>
                    -->
                    <ul class="activity-list" style="height: 600px !important; overflow: scroll;">
                        {% for module in module_list %}
                        <li class="drag-item" style="margin: 4px">
                            <div class="row-fluid" style="margin: 2px">
                                <a class="nopadding pull-left"><i class="icon-tasks" style="margin-right: 6px"></i></a>
                                <a class="nopadding pull-left add-job" module_id="{{ module.id }}" module_name="{{ module.name }}"><label>{{ module.name }}</label></a>
                                <a class="tip pull-right nopadding module_link" href="#" title="see details" module_id="{{ module.id }}">
                                    <i class="icon-double-angle-right"></i>
                                </a>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </div>

    <div class="processing_fade" id="saving_fade"></div>
    <div class="processing_modal" id="saving_modal">
        <img id="loader" src="{{ STATIC_URL }}img/loading.gif" />
    </div>
    {% include 'project/project_job_new.html' %}
    {% include 'project/project_execute.html' %}
{% endblock %}

project/templates/project/project_executing.html
{% extends "base.html" %}
{% block header %}
    <a href="/project/executing/index" title="Go to Scheduled" class="tip-bottom"><i class="icon-tasks"></i> Executing</a>
{% endblock %}

{% block script %}
    <script src="{{ STATIC_URL }}js/project/project_executing.js"></script>
{% endblock %}

{% block main_panel %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span9">
                <h4><strong>Executing Flows</strong></h4>
            </div>
        </div>
        <hr style="margin: 2px"/>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
                      <h5></h5>
                    </div>
                    <div class="widget-content nopadding">
                        <table class="table table-bordered data-table ">
                            <thead>
                                <tr>
                                    <th>Execution Id</th>
                                    <th>Flow</th>
                                    <th>Project</th>
                                    <th>User</th>
                                    <th>Proxy User</th>
                                    <th>Start Time</th>
                                    <th>End Time</th>
                                    <th>Elapsed</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for executing_item in executing_list %}
                                <tr class="gradeA">
                                    <td>
                                        <a href="/project/execution/index?execution_id={{ executing_item.id }}">
                                            {{ executing_item.id }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="/project/flow/index?project_id={{ executing_item.project_id }}&version_id={{ executing_item.project_version }}&job_id={{ executing_item.flow_id }}">
                                            {{ executing_item.flow }}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="/project/manage?project_id={{ executing_item.project_id }}&version_id={{ executing_item.project_version }}">
                                            {{ executing_item.project }}
                                        </a>
                                    </td>
                                    <td>{{ executing_item.user }}</td>
                                    <td>{{ executing_item.proxy_user }}</td>
                                    <td>{{ executing_item.start_time }}</td>
                                    <td>-</td>
                                    <td>-</td>
                                    <td><span class="badge badge-info">Running</span></td>
                                    <td></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>
              </div>
        </div>
    </div>
{% endblock %}

project/templates/project/project_flow_execution.html
{% extends "base.html" %}

{% block script %}
    <script src="{{ STATIC_URL }}js/project/diagram.js"></script>
    <script src="{{ STATIC_URL }}js/project/project_flow_execution.js"></script>
    <script src="{{ STATIC_URL }}js/project/project_execute.js"></script>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/project_flow_execution.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/diagram.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/project_execute.css" />
{% endblock %}

{% block header %}
    <a href="/project/index" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Projects</a>
    <a href="/project/manage?project_id={{ project_id }}&version_id={{ project_version }}">Manage</a>
    <a href="/project/flow/index?project_id={{ project_id }}&version_id={{ project_version }}&job_id={{ flow_id }}">Flow</a>
    <a href="#">Execution</a>
{% endblock %}

{% block main_panel %}
    <div class="container-fluid main_panel" execution_id="{{ execution_id }}" project_id="{{ project_id }}" project_version="{{ project_version }}" flow_id="{{ flow_id }}">
        <div class="row-fluid">
            <div class="span8">
                <h4><strong>Flow </strong>{{ flow_name }}</h4>
                <h5><strong>Project </strong> {{ project_name }}</h5>
            </div>
            <div class="span4">
                <button class="btn btn-info" id="btn_execution_rerun" style="margin-left: 10px; display: none">Rerun</button>
                <button class="btn btn-primary" id="btn_execution_pause" style="margin-left: 10px; display: none">Pause</button>
                <button class="btn btn-danger" id="btn_execution_cancel" style="margin-left: 10px; display: none">Cancel</button>
                <button class="btn btn-default" id="btn_execution_resume" style="margin-left: 10px; display: none">Resume</button>
            </div>
        </div>
        <hr style="margin: 2px"/>
        <div class="row-fluid">

            <div class="span12">
                <div class="widget-box">
                  <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab1">Graph</a></li>
                        <li><a data-toggle="tab" href="#tab2">Job List</a></li>
                        <li><a data-toggle="tab" href="#tab3">Flow Log</a></li>
                    </ul>
                  </div>
                  <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="diagram_panel" id="flow_diagram_panel">
                        </div>
                    </div>
                    <div id="tab2" class="tab-pane">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Name</th>
                                <th>Timeline</th>
                                <th>Start Time</th>
                                <th>End Time</th>
                                <th>Elapsed</th>
                                <th>Status</th>
                                <th>Logs</th>
                            </tr>
                          </thead>
                          <tbody>
                              {% for job in execution_jos %}
                              <tr class="gradeA">
                                  <td>
                                      <a href="">{{ job.job_name }}</a>
                                  </td>
                                  <td>
                                      <div class="progress progress-success" style="margin-bottom: 0px;">
                                          <div style="width: {{ job.timeline_width }}; margin-left: {{ job.timeline_margin_left }}" class="bar"></div>
                                      </div>
                                  </td>
                                  <td>{{ job.start_time }}</td>
                                  <td>{{ job.end_time }}</td>
                                  <td>{{ job.elapsed }}</td>
                                  <td><span class="{{ job.badge_class }} badge block">{{ job.status }}</span></td>
                                  <td><a href="/project/execution/job/index?execution_id={{ execution_id }}&job_id={{ job.job_id }}">Log</a></td>
                              </tr>
                              {% endfor %}
                          </tbody>
                        </table>
                    </div>
                    <div id="tab3" class="tab-pane">
                        <button class="btn btn-default" id="log_refresh">Refresh</button>
                        <hr style="margin: 10px"/>
                        <textarea class="span12 log_panel" rows="40" readonly="readonly" log_offset="{{ log_offset }}">{{ log_data }}</textarea>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>

    {% include 'project/project_execute.html' %}
{% endblock %}

project/templates/project/project_history.html
{% extends "base.html" %}

{% load i18n %}

{% block header %}
    <a href="/project/history/index" title="Go to History" class="tip-bottom"><i class="icon-tasks"></i> History</a>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/project/project_history.css" />
{% endblock %}

{% block script %}
    <script src="{{ STATIC_URL }}js/project/project_history.js"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = '{% url "project:history_table" %}';
        // translations for datatables
        var oLanguages = {
            oPaginate:{
                sFirst:'First',
                sLast: 'Last',
                sNext: 'Next',
                sPrevious: 'Previous'
            },
            sInfo:'{% trans "Showing _START_ to _END_ of _TOTAL_ entries" %}',
            sInfoEmpty: '{% trans "No entries to show" %}',
            sInfoFiltered: '{% trans "(filtered from _MAX_ total entries)" %}',
            sLengthMenu:'{% trans "Show _MENU_ entries" %}',
            sProcessing: '{% trans "Processing" %}',
            sSearch: '{% trans "Filter records:" %}',
            sZeroRecords: '{% trans "No data to show" %}'
        };
    </script>
{% endblock %}

{% block main_panel %}
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span9">
                <h4><strong>History</strong></h4>
            </div>
        </div>
        <hr style="margin: 2px"/>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-th"></i> </span>
                      <h5>History</h5>
                    </div>
                    <div class="widget-content nopadding">
                        <!--table class="table table-bordered data-table " id="history_table"-->
                        <table class="table table-bordered" id="history_table">
                            <thead>
                                <th>{% trans "ID" %}</th>
                                <th>{% trans "Flow" %}</th>
                                <th>{% trans "Project" %}</th>
                                <th>{% trans "User" %}</th>
                                <th>{% trans "Start Time" %}</th>
                                <th>{% trans "End Time" %}</th>
                                <th>{% trans "Elapsed" %}</th>
                                <th>{% trans "Status" %}</th>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}