auth/urls.py
from django.conf.urls import url, patterns
import views

urlpatterns = patterns("", )

collie/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', RedirectView.as_view(url='/project/index', permanent=False), name='index'),
                       url(r'^index/$', RedirectView.as_view(url='/project/index', permanent=False), name='index'),
                       # account login/logout
                       # url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html',
                       #                                                      'redirect_field_name': 'next'}),
                       # url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/index/'}),
                       #et
                       url(r'^accounts/login/$', 'django_cas.views.login'),
                       url(r'^accounts/logout/$', 'django_cas.views.logout'),

                       url(r'^admin/', include(admin.site.urls)),


                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^module/', include('module.urls')),
                       url(r'^auth/', include('auth.urls')),
                       url(r'^profile/', include('profiles.urls')),
                       # url(r'^project/', include('project.urls', namespace='project')))
                       url(r'^project/', include('project.urls', namespace='project')),
                       url(r'^data/', include('data.urls', namespace='data')),
                       url(r'^table/', include('table.urls', namespace='table')))

templates/base.html
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Collie</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/bootstrap-responsive.min.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/fullcalendar.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/matrix-style.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/matrix-media.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/datepicker.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/select2.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/uniform.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/jquery.gritter.css"/>
    <link rel="stylesheet" href="{{ STATIC_URL }}jQuery-contextMenu/jquery.contextMenu.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}uploadify/uploadify.css" />
    <link rel='stylesheet' href="{{ STATIC_URL }}css/fonts-googleapis.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/processing.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}datetimepicker/jquery.datetimepicker.css">
    {% block css %}
    {% endblock %}
</head>
<body>

<!--Header-part-->
<div id="header">
    <h1><a href="dashboard.html">Matrix Admin</a></h1>
</div>
<!--close-Header-part-->

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
    <ul class="nav">
        <li class="dropdown" id="">
            <a title="" href="/static/data-platform-fe/dist/"> <!-- TODO -->
                <i class="icon icon-cloud"></i>
                <span class="text">Data</span>
                <span class="label label-important">New!</span>
            </a>
        </li>
        <li class="dropdown" id="">
            <a title="" href="/profile/index">
                <i class="icon icon-user"></i>
                <span class="text">Profile</span>
            </a>
        </li>
        <li class="dropdown" id="">
            <a title="" href="/static/doc/collie_manual.pdf" target="window">
                <i class="icon icon-book"></i>
                <span class="text">Manual</span>
            </a>
        </li>
        <li class="dropdown" id="">
            <a title="" href="http://wiki.mioffice.cn/xmg/Collie" target="window">
                <i class="icon icon-question-sign"></i>
                <span class="text">Wiki</span>
            </a>
        </li>
        <!-- TODO
        <li class="dropdown" id="profile-messages">
            <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle">
                <i class="icon icon-user"></i>
                <span class="text">Welcome User</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                <li class="divider"></li>
                <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                <li class="divider"></li>
                <li><a href="/logout/"><i class="icon-key"></i> Log Out</a></li>
            </ul>
        </li>
        <li class="dropdown" id="menu-messages">
            <a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle">
                <i class="icon icon-envelope"></i>
                <span class="text">Messages</span>
                <span class="label label-important">5</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
                <li class="divider"></li>
                <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
                <li class="divider"></li>
                <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
                <li class="divider"></li>
                <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
            </ul>
        </li>
        <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
        -->
        <li class=""><a title="" href="/accounts/logout/"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a>
        </li>
        <li class="dropdown" id="">
            <a title="">
                <span class="text">Welcome {{ user.username }}</span>
            </a>
        </li>
    </ul>
</div>
<!--close-top-Header-menu-->
<!--start-top-serch-->
<!-- TODO
<div id="search">
    <input type="text" placeholder="Search here..."/>
    <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
</div>
-->
<!--close-top-serch-->
<!--sidebar-menu-->
<div id="sidebar"><a href="" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>
    <ul>
        <li id="bar-projects">
            <a href="{% url 'project:index' %}">
                <i class="icon icon-home"></i>
                <span>Projects</span>
            </a>
        </li>
        <li id="bar-scheduled">
            <a href="/project/scheduled/index">
                <i class="icon icon-signal"></i>
                <span>Scheduled</span>
            </a>
        </li>
        <li id="bar-executing">
            <a href="/project/executing/index">
                <i class="icon icon-inbox"></i>
                <span>Executing</span>
            </a>
        </li>
        <li id="bar-history">
            <a href="/project/history/index">
                <i class="icon icon-th"></i>
                <span>History</span>
            </a>
        </li>
        <!--
        <li id="bar-table">
            <a href="/table/index">
                <i class="icon icon-cloud"></i>
                <span>Tables</span>
            </a>
        </li>
        -->
        <li id="bar-module">
            <a href="/module/index">
                <i class="icon icon-th-list"></i>
                <span>Modules</span>
            </a>
        </li>
    </ul>
</div>
<!--sidebar-menu-->

<!--main-container-part-->
<div id="content">
    <!--breadcrumbs-->
    <div id="content-header">
        <div id="breadcrumb">
            {% block header %}
            {% endblock %}
        </div>
    </div>
    <!--End-breadcrumbs-->

    <!--Action boxes-->
    {% block main_panel %}
    {% endblock %}
</div>

<!--end-main-container-part-->

<!--Footer-part-->

<div class="row-fluid">
    <div id="footer" class="span12"> 2013 &copy; SNS. Brought to you by <a href="http://www.xiaomi.com/">Xiaomi.com</a>
    </div>
</div>

<!--end-Footer-part-->

<script src="{{ STATIC_URL }}matrix-admin/js/excanvas.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.ui.custom.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.flot.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.flot.resize.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.peity.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/fullcalendar.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/matrix.js"></script>
<!--script src="{{ STATIC_URL }}matrix-admin/js/matrix.dashboard.js"></script-->
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.gritter.min.js"></script>
<!--script src="{{ STATIC_URL }}matrix-admin/js/matrix.interface.js"></script-->
<!--script src="{{ STATIC_URL }}matrix-admin/js/matrix.chat.js"></script-->
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.validate.js"></script>
<!--script src="{{ STATIC_URL }}matrix-admin/js/matrix.form_validation.js"></script-->
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.wizard.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.uniform.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/select2.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/matrix.popover.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/bootstrap-datepicker.js"></script>
<script src="{{ STATIC_URL }}jQuery-contextMenu/jquery.contextMenu.js"></script>
<script src="{{ STATIC_URL }}uploadify/swfobject.js" xmlns="http://www.w3.org/1999/html"></script>
<script src="{{ STATIC_URL }}uploadify/jquery.uploadify.v2.1.4.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.jsPlumb-1.5.5-min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/jquery.dataTables.min.js"></script>
<script src="{{ STATIC_URL }}matrix-admin/js/matrix.tables.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootbox.min.js"></script>
<script src="{{ STATIC_URL }}js/processing.js"></script>
<script src="{{ STATIC_URL }}datetimepicker/jquery.datetimepicker.js"></script>
<script src="{{ STATIC_URL }}js/resumable.js"></script>
<script type="text/javascript">

    // This function is called from the pop-up menus to transfer to
    // a different page. Ignore if the value returned is a null string:
    function goPage(newURL) {

        // if url is empty, skip the menu dividers and reset the menu selection to default
        if (newURL != "") {

            // if url is "-", it is this page -- reset the menu:
            if (newURL == "-") {
                resetMenu();
            }
            // else, send page to designated URL
            else {
                document.location.href = newURL;
            }
        }
    }

    // resets the menu selection upon entry to this page:
    function resetMenu() {
        document.gomenu.selector.selectedIndex = 2;
    }

    // String.format
    String.format = function () {
        if (arguments.length == 0) {
            return null;
        }
        var str = arguments[0];
        for (var i = 1; i < arguments.length; i++) {
            var re = new RegExp('\\{' + (i - 1) + '\\}', 'gm');
            str = str.replace(re, arguments[i]);
        }
        return str;
    };

    // get parameter value from access url
    function getURLParameter(sParam) {
        var sPageURL = window.location.search.substring(1);
        var sURLVariables = sPageURL.split('&');
        for (var i = 0; i < sURLVariables.length; i++) {
            var sParameterName = sURLVariables[i].split('=');
            if (sParameterName[0] == sParam) {
                return sParameterName[1];
            }
        }
    }
</script>

{% block script %}
{% endblock %}

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <title>Collie</title><meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/css/matrix-login.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}matrix-admin/font-awesome/css/font-awesome.css" />
    <link rel='stylesheet' href="{{ STATIC_URL }}css/fonts-googleapis.css" />
</head>
<body>
    <div id="loginbox">
        <form id="loginform" class="form-vertical" role="form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
            {% csrf_token %}
            <div class="control-group normal_text"> <h3><img src="{{ STATIC_URL }}matrix-admin/img/dog3.png" alt="Logo" /></h3></div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_lg"><i class="icon-user"></i></span>
                        <input class="form-control" type="text" placeholder="Username (Sign in with Xiaomi Email Account)" id="{{ form.username.id_for_lable }}" name="{{ form.username.html_name }}"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="main_input_box">
                        <span class="add-on bg_ly"><i class="icon-lock"></i></span>
                        <input class="form-control" type="password" placeholder="Password" id="{{ form.password.id_for_lable }}" name="{{ form.password.html_name }}"/>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <span class="pull-right"><button type="submit" class="btn btn-success"> Login</button></span>
            </div>
        </form>
    </div>

    <script src="{{ STATIC_URL }}matrix-admin/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}matrix-admin/js/matrix.login.js"></script>
</body>

</html>